application: no-ref
version: 1
runtime: python
api_version: 1

handlers:
<<<<<<< HEAD
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/images/favicon.ico
  mime_type: image/x-icon
=======
- url: /favicon.ico$
  static_dir: static
>>>>>>> no-ref/master
- url: /static
  static_dir: static
  
- url: .*
  script: main.py
