application: no-ref
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/images/favicon.ico
  mime_type: image/x-icon
- url: /static
  static_dir: static
  
- url: .*
  script: main.py
